### PR TITLE
Update PolygonTest.java

### PR DESCRIPTION
**Pull request by PigneInTesta**
Add another test for irregular/not common polygon

### CODE REVIEW

**Comment by nbicocchi** [comment]
Good idea!

**Comment by Bert0ns** [comment]
May I ask why the tests on `toString()` have been removed? 

I was wandering if it is an error or a decision

Thanks

**Comment by PigneInTesta** [comment]
Obviously an error, if you want you can add it or I will do this afternoon...thanks!

**Comment by nbicocchi** [comment]
I already pushed it back. However, in general, it does not make much sense to test getters and toString. Instead, it might be worth testing setters expecially if they implement some kind of controls.

**Comment by PigneInTesta** [comment]
Thanks for the advice

**Pull request merged**
